services:
  - type: web
    name: beacon
    env: python
    plan: starter
    buildCommand: chmod +x build.sh && ./build.sh
    # Render automatically provides PORT environment variable
    # Hypercorn binds to this port and Render handles the routing
    startCommand: hypercorn app:application --bind "0.0.0.0:$PORT" --worker-class asyncio --workers 1 --access-logfile - --error-logfile - --keep-alive 120 --graceful-timeout 120 --websocket-ping-interval 20
    healthCheckPath: /health
    healthCheckTimeout: 100
    autoDeploy: true
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.11
      - key: FLASK_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: beacon-db
          property: connectionString
      - key: REDIS_URL
        value: "https://rare-dory-16482.upstash.io"
      - key: REDIS_TOKEN
        sync: false
      - key: OPENAI_API_KEY
        sync: false
      - key: FLASK_SECRET_KEY
        generateValue: true
      - key: EMAIL
        sync: false
      - key: IMAP_PASSWORD
        sync: false
      - key: TINYMCE_API_KEY
        sync: false
      - key: RENDER
        value: "true"
      - key: PIP_NO_CACHE_DIR
        value: "false"
      - key: TORCH_CPU_ONLY
        value: "true"
      - key: HYPERCORN_GRACEFUL_TIMEOUT
        value: "120"
      - key: HYPERCORN_WORKER_CLASS
        value: "asyncio"
      - key: HYPERCORN_KEEP_ALIVE_TIMEOUT
        value: "120"

databases:
  - name: beacon-db
    databaseName: beacon
    plan: free 