name: Documentation Checks

on:
  pull_request:
    branches:
      - main  # Change this to your default branch if different

jobs:
  doc-checks:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'  # Adjust to your Python version if needed

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          # Install interrogate for docstring checking
          pip install interrogate

      - name: Check docstrings
        run: python scripts/check_docstrings.py app --min-coverage 95.0

      - name: Check READMEs
        run: cd docs && make check-readme
